<?php

namespace LaraGram\Laraquest\Updates;

/**
 * @property int $message_id
 * @property int $message_thread_id
 * @property DirectMessagesTopic $direct_messages_topic
 * @property User $from
 * @property Chat $sender_chat
 * @property int $sender_boost_count
 * @property User $sender_business_bot
 * @property int $date
 * @property string $business_connection_id
 * @property Chat $chat
 * @property MessageOrigin $forward_origin
 * @property true $is_topic_message
 * @property true $is_automatic_forward
 * @property Message $reply_to_message
 * @property ExternalReplyInfo $external_reply
 * @property TextQuote $quote
 * @property Story $reply_to_story
 * @property int $reply_to_checklist_task_id
 * @property User $via_bot
 * @property int $edit_date
 * @property true $has_protected_content
 * @property true $is_from_offline
 * @property true $is_paid_post
 * @property string $media_group_id
 * @property string $author_signature
 * @property int $paid_star_count
 * @property string $text
 * @property MessageEntity[] $entities
 * @property LinkPreviewOptions $link_preview_options
 * @property SuggestedPostInfo $suggested_post_info
 * @property string $effect_id
 * @property Animation $animation
 * @property Audio $audio
 * @property Document $document
 * @property PaidMediaInfo $paid_media
 * @property PhotoSize[] $photo
 * @property Sticker $sticker
 * @property Story $story
 * @property Video $video
 * @property VideoNote $video_note
 * @property Voice $voice
 * @property string $caption
 * @property MessageEntity[] $caption_entities
 * @property true $show_caption_above_media
 * @property true $has_media_spoiler
 * @property Checklist $checklist
 * @property Contact $contact
 * @property Dice $dice
 * @property Game $game
 * @property Poll $poll
 * @property Venue $venue
 * @property Location $location
 * @property User[] $new_chat_members
 * @property User $left_chat_member
 * @property string $new_chat_title
 * @property PhotoSize[] $new_chat_photo
 * @property true $delete_chat_photo
 * @property true $group_chat_created
 * @property true $supergroup_chat_created
 * @property true $channel_chat_created
 * @property MessageAutoDeleteTimerChanged $message_auto_delete_timer_changed
 * @property int $migrate_to_chat_id
 * @property int $migrate_from_chat_id
 * @property MaybeInaccessibleMessage $pinned_message
 * @property Invoice $invoice
 * @property SuccessfulPayment $successful_payment
 * @property RefundedPayment $refunded_payment
 * @property UsersShared $users_shared
 * @property ChatShared $chat_shared
 * @property GiftInfo $gift
 * @property string $connected_website
 * @property WriteAccessAllowed $write_access_allowed
 * @property PassportData $passport_data
 * @property ProximityAlertTriggered $proximity_alert_triggered
 * @property ChatBoostAdded $boost_added
 * @property ChatBackground $chat_background_set
 * @property ChecklistTasksDone $checklist_tasks_done
 * @property ChecklistTasksAdded $checklist_tasks_added
 * @property DirectMessagePriceChanged $direct_message_price_changed
 * @property ForumTopicCreated $forum_topic_created
 * @property ForumTopicEdited $forum_topic_edited
 * @property ForumTopicClosed $forum_topic_closed
 * @property ForumTopicReopened $forum_topic_reopened
 * @property GeneralForumTopicHidden $general_forum_topic_hidden
 * @property GeneralForumTopicUnhidden $general_forum_topic_unhidden
 * @property GiveawayCreated $giveaway_created
 * @property Giveaway $giveaway
 * @property GiveawayWinners $giveaway_winners
 * @property GiveawayCompleted $giveaway_completed
 * @property PaidMessagePriceChanged $paid_message_price_changed
 * @property SuggestedPostApproved $suggested_post_approved
 * @property SuggestedPostApprovalFailed $suggested_post_approval_failed
 * @property SuggestedPostDeclined $suggested_post_declined
 * @property SuggestedPostPaid $suggested_post_paid
 * @property SuggestedPostRefunded $suggested_post_refunded
 * @property VideoChatScheduled $video_chat_scheduled
 * @property VideoChatStarted $video_chat_started
 * @property VideoChatEnded $video_chat_ended
 * @property VideoChatParticipantsInvited $video_chat_participants_invited
 * @property WebAppData $web_app_data
 * @property InlineKeyboardMarkup $reply_markup
 **/
class Message { }